# This YAML file is for creating an environment using conda-store (https://conda.store/),
# an environment management tool integrated in Nebari.

channels:
  - conda-forge
  - microsoft
dependencies:
  - python=3.10
  - pandas
  - ipykernel
  - ipywidgets
  - panel
  - hvplot
  - geoviews
  - pyarrow
  - nebari-dask
  - gcsfs
  - python-graphviz
  - ipycytoscape
  - jhsingle-native-proxy
  - bokeh-root-cmd
  - nbconvert
  name: data-of-unusual-size
