channels:
- conda-forge
- microsoft
dependencies:
- python=3.10
- ipykernel
- panel
- hvplot
- pandas
- hvplot
- pyarrow
- playwright # needed to download the data from the bts website
- typer
- nebari-dask
- s3fs
description: 'Environment for the Data of an Unusual Size tutorial at PyCon US 2023'
name: pycon2023
